name: Build and Deploy

on:
  push:
    branches:
      - master

env:
  AWS_REGION: ap-south-1
  ECS_CLUSTER: demo_cluster
  CONTAINER_NAME: demo-app
  ECS_SERVICE: demo_service
  ECS_TD: .github/workflows/td.json
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm install
      - name: Build Express app
        run: npm run build
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        
      - name: Terraform Init
        run: |
          cd erc
          terraform init
      - name: Creating ECR
        run: |
          cd erc
          terraform plan
