name: Build and Deploy

on:
  push:
    branches:
      - master

env:
  AWS_REGION: ap-south-1
  ECS_CLUSTER: demo_cluster
  CONTAINER_NAME: demo-app
  ECS_SERVICE: demo_service
  ECS_TD: .github/workflows/td.json
  TERRAFORM_CLI_PATH: /home/pawan/linux/demo
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm install
      - name: Build Express app
        run: npm run build
      - name: Setup Terraform 
        run: |
          wget https://releases.hashicorp.com/terraform/1.0.7/terraform_1.0.7_linux_amd64.zip
          unzip terraform_1.0.7_linux_amd64.zip
          sudo mv terraform /usr/local/bin/

        
      - name: Terraform Init
        run: terraform init
      - name: Creating ECR
        run: |
          cd erc
          terraform plan
